environment:
  global:
    LIBRDKAFKA_NUGET_VERSION: 0.11.6-RC2
    CIBW_TEST_REQUIRES: pytest requests avro
    CIBW_TEST_COMMAND: "pytest --import-mode=append --ignore={project}\\tests\\avro {project}\\tests"
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"

build_script:
#  - dir /s c:\python27
  - echo %CD%
  - dir
  - "curl https://raw.githubusercontent.com/chemeris/msinttypes/master/inttypes.h -o c:\\python27\\include\\inttypes.h"
  - "curl https://raw.githubusercontent.com/chemeris/msinttypes/master/stdint.h -o c:\\python27\\include\\stdint.h"
  - nuget install librdkafka.redist -version %LIBRDKAFKA_NUGET_VERSION% -OutputDirectory dest
  - xcopy /I /F /S dest\librdkafka.redist.%LIBRDKAFKA_NUGET_VERSION%\build\native\include\* C:\python27\include
  - xcopy /F dest\librdkafka.redist.%LIBRDKAFKA_NUGET_VERSION%\build\native\lib\win\x86\win-x86-Release\v120\librdkafka.lib C:\python27\libs\librdkafka.lib*
  - xcopy /F dest\librdkafka.redist.%LIBRDKAFKA_NUGET_VERSION%\build\native\lib\win\x86\win-x86-Release\v120\librdkafka.lib C:\python27\libs\rdkafka.lib*
  - xcopy /F dest\librdkafka.redist.%LIBRDKAFKA_NUGET_VERSION%\runtimes\win-x86\native\librdkafka.dll C:\python27\libs\rdkafka.dll*
  - xcopy /F dest\librdkafka.redist.%LIBRDKAFKA_NUGET_VERSION%\runtimes\win-x86\native\*.dll %CD%
  - xcopy /I /F /S dest\librdkafka.redist.%LIBRDKAFKA_NUGET_VERSION%\runtimes\win-x86\native\* C:\python27\libs
  - pip install cibuildwheel
  - cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
